# The docker-compose DSL syntax format we're using
version: "2.1"

services:

  shopify_app:
    build: ./
    volumes:
      - "./:/usr/src/app"
    container_name: shopify_app 
    ports:
      - "3000:3000"
    command: "npm run dev"
    environment:
      PORT: 3000
