# The docker-compose DSL syntax format we're using
version: "2.1"

services:
  webserver:
    build: ./
    volumes:
      - "./:/usr/src/app"
    container_name: node_app
    ports:
      - "3000:3000"
    command: "node -e \"setInterval( () => {}, 60000 )\""
